version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing Composer and dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
      - echo "Composer dependencies installed."

      - echo "Installing additional dependencies..."
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update
      - apt-get install -y sqlite3
      - echo "Additional dependencies installed."

  pre_build:
    commands:
      - echo "🔧 Preparing Laravel environment..."

      # Check if .env.production exists, then copy it
      - if [ -f .env.production ]; then cp .env.production .env; else cp .env.example .env; fi

      # (Optional) Create SQLite file if using SQLite
      - if grep -q "DB_CONNECTION=sqlite" .env; then touch database/database.sqlite; fi

      - echo "🧪 Running Laravel migrations..."
      - php artisan migrate --force

      - echo "🔑 Generating application key..."
      - php artisan key:generate --force

      - echo "🚀 Optimizing Laravel..."
      - php artisan optimize

  build:
    commands:
      - echo "🧪 Running Laravel Tests..."
      - php artisan test

      - echo "✅ Build completed."

  post_build:
    commands:
      - echo "🚀 Deployment ready! Triggering post-deployment hook..."
