version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing Composer and dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-interaction --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo "🔧 Preparing Laravel environment..."

      # Check if .env.production exists, then copy it
      - if [ -f .env.production ]; then cp .env.production .env; else cp .env.example .env; fi

      # (Optional) Create SQLite file if using SQLite
      - if grep -q "DB_CONNECTION=sqlite" .env; then touch database/database.sqlite; fi

      - echo "🧪 Running Laravel migrations..."
      - php artisan migrate --force

      # Laravel Cache Optimization
      - php artisan optimize

      - php artisan key:generate --force

  build:
    commands:
      - echo "🧪 Running Laravel Tests..."
      - php artisan test || true # You can fail the build if test fails

      - echo "✅ Build completed."

  post_build:
    commands:
      - echo "🚀 Deployment ready! Triggering post-deployment hook..."
